### ISSUE TITLE
store API changes

### ISSUE THREAD

**Issue by suhasdeshpande** [johnlindquist/egghead-nuxt#1]
store/index.js expects a function state instead of an object due to [this](https://github.com/nuxt/nuxt.js/issues/754)

current
```
export const state = {
  counter: 1
}
```

With breaking change
```
export const state = () => ({
  counter: 1
})
```

I just started taking the course. Do you want me to send a PR for this change?

**Comment by johnlindquist** [comment]
@suhasdeshpande I plan on updating the lessons once nuxt 1.0 releases.

**Comment by suhasdeshpande** [comment]
Cool. The course is very useful. Thank you very much.
